name: release

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  xmake:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Checkout submodules
        run: |
          git submodule sync --recursive
          git submodule update --init --recursive

      - name: Setup XMake
        uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: "latest"

      - name: Build
        run: |
          git checkout main
          git submodule sync --recursive
          git submodule update --init --recursive
          xmake f -y --mode=releasedbg
          xmake build -y -vD
          mkdir artifacts\F4SE\Plugins
          copy build\windows\x64\releasedbg\QuickUserSaves.dll artifacts\F4SE\Plugins\
          copy build\windows\x64\releasedbg\QuickUserSaves.pdb artifacts\F4SE\Plugins\

      - name: Zip combined artifact
        run: |
          cd artifacts
          7z a -t7z -mx=9 ..\QuickUserSaves.7z .

      - name: Upload artifact to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: QuickUserSaves.7z
